package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Demandapply generated by hbm2java
 */
@Entity
@Table(name="demandapply"
    ,schema="dbo"
    ,catalog="SptEducation"
)
public class Demandapply  implements java.io.Serializable {


     private String userId;
     private String daidcardPhoto;
     private String dapersonDescribe;

    public Demandapply() {
    }

	
    public Demandapply(String userId) {
        this.userId = userId;
    }
    public Demandapply(String userId, String daidcardPhoto, String dapersonDescribe) {
       this.userId = userId;
       this.daidcardPhoto = daidcardPhoto;
       this.dapersonDescribe = dapersonDescribe;
    }
   
     @Id 

    
    @Column(name="UserId", unique=true, nullable=false, length=30)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="DAIdcardPhoto", length=50)
    public String getDaidcardPhoto() {
        return this.daidcardPhoto;
    }
    
    public void setDaidcardPhoto(String daidcardPhoto) {
        this.daidcardPhoto = daidcardPhoto;
    }

    
    @Column(name="DAPersonDescribe", length=200)
    public String getDapersonDescribe() {
        return this.dapersonDescribe;
    }
    
    public void setDapersonDescribe(String dapersonDescribe) {
        this.dapersonDescribe = dapersonDescribe;
    }




}


