package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DemandsignupId generated by hbm2java
 */
@Embeddable
public class DemandsignupId  implements java.io.Serializable {


     private Date dstime;
     private String userId;
     private Date demandTime;
     private String demandId;

    public DemandsignupId() {
    }

    public DemandsignupId(Date dstime, String userId, Date demandTime, String demandId) {
       this.dstime = dstime;
       this.userId = userId;
       this.demandTime = demandTime;
       this.demandId = demandId;
    }
   


    @Column(name="DSTime", nullable=false, length=23)
    public Date getDstime() {
        return this.dstime;
    }
    
    public void setDstime(Date dstime) {
        this.dstime = dstime;
    }


    @Column(name="UserId", nullable=false, length=20)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }


    @Column(name="DemandTime", nullable=false, length=23)
    public Date getDemandTime() {
        return this.demandTime;
    }
    
    public void setDemandTime(Date demandTime) {
        this.demandTime = demandTime;
    }


    @Column(name="DemandId", nullable=false, length=30)
    public String getDemandId() {
        return this.demandId;
    }
    
    public void setDemandId(String demandId) {
        this.demandId = demandId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DemandsignupId) ) return false;
		 DemandsignupId castOther = ( DemandsignupId ) other; 
         
		 return ( (this.getDstime()==castOther.getDstime()) || ( this.getDstime()!=null && castOther.getDstime()!=null && this.getDstime().equals(castOther.getDstime()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getDemandTime()==castOther.getDemandTime()) || ( this.getDemandTime()!=null && castOther.getDemandTime()!=null && this.getDemandTime().equals(castOther.getDemandTime()) ) )
 && ( (this.getDemandId()==castOther.getDemandId()) || ( this.getDemandId()!=null && castOther.getDemandId()!=null && this.getDemandId().equals(castOther.getDemandId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDstime() == null ? 0 : this.getDstime().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getDemandTime() == null ? 0 : this.getDemandTime().hashCode() );
         result = 37 * result + ( getDemandId() == null ? 0 : this.getDemandId().hashCode() );
         return result;
   }   


}


