package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Demandsignup generated by hbm2java
 */
@Entity
@Table(name="demandsignup"
    ,schema="dbo"
    ,catalog="SptEducation"
)
public class Demandsignup  implements java.io.Serializable {


     private DemandsignupId id;
     private String demandTitle;

    public Demandsignup() {
    }

	
    public Demandsignup(DemandsignupId id) {
        this.id = id;
    }
    public Demandsignup(DemandsignupId id, String demandTitle) {
       this.id = id;
       this.demandTitle = demandTitle;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="dstime", column=@Column(name="DSTime", nullable=false, length=23) ), 
        @AttributeOverride(name="userId", column=@Column(name="UserId", nullable=false, length=20) ), 
        @AttributeOverride(name="demandTime", column=@Column(name="DemandTime", nullable=false, length=23) ), 
        @AttributeOverride(name="demandId", column=@Column(name="DemandId", nullable=false, length=30) ) } )
    public DemandsignupId getId() {
        return this.id;
    }
    
    public void setId(DemandsignupId id) {
        this.id = id;
    }

    
    @Column(name="DemandTitle", length=50)
    public String getDemandTitle() {
        return this.demandTitle;
    }
    
    public void setDemandTitle(String demandTitle) {
        this.demandTitle = demandTitle;
    }




}


