package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GoodsdemandId generated by hbm2java
 */
@Embeddable
public class GoodsdemandId  implements java.io.Serializable {


     private String userId;
     private Date demandTime;

    public GoodsdemandId() {
    }

    public GoodsdemandId(String userId, Date demandTime) {
       this.userId = userId;
       this.demandTime = demandTime;
    }
   


    @Column(name="UserId", nullable=false, length=30)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }


    @Column(name="DemandTime", nullable=false, length=23)
    public Date getDemandTime() {
        return this.demandTime;
    }
    
    public void setDemandTime(Date demandTime) {
        this.demandTime = demandTime;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GoodsdemandId) ) return false;
		 GoodsdemandId castOther = ( GoodsdemandId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getDemandTime()==castOther.getDemandTime()) || ( this.getDemandTime()!=null && castOther.getDemandTime()!=null && this.getDemandTime().equals(castOther.getDemandTime()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getDemandTime() == null ? 0 : this.getDemandTime().hashCode() );
         return result;
   }   


}


