package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Goodsdemand generated by hbm2java
 */
@Entity
@Table(name="goodsdemand"
    ,schema="dbo"
    ,catalog="SptEducation"
)
public class Goodsdemand  implements java.io.Serializable {


     private GoodsdemandId id;
     private String demandTitle;
     private String demandSide;
     private String demandCity;
     private String demandAddress;
     private String demandPerson;
     private String demandTel;
     private String demandGoods;
     private Date demandValidity;
     private String demandContent;
     private String demandPicture;
     private String demandVideo;
     private String demandStatus;

    public Goodsdemand() {
    }

	
    public Goodsdemand(GoodsdemandId id) {
        this.id = id;
    }
    public Goodsdemand(GoodsdemandId id, String demandTitle, String demandSide, String demandCity, String demandAddress, String demandPerson, String demandTel, String demandGoods, Date demandValidity, String demandContent, String demandPicture, String demandVideo, String demandStatus) {
       this.id = id;
       this.demandTitle = demandTitle;
       this.demandSide = demandSide;
       this.demandCity = demandCity;
       this.demandAddress = demandAddress;
       this.demandPerson = demandPerson;
       this.demandTel = demandTel;
       this.demandGoods = demandGoods;
       this.demandValidity = demandValidity;
       this.demandContent = demandContent;
       this.demandPicture = demandPicture;
       this.demandVideo = demandVideo;
       this.demandStatus = demandStatus;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="UserId", nullable=false, length=30) ), 
        @AttributeOverride(name="demandTime", column=@Column(name="DemandTime", nullable=false, length=23) ) } )
    public GoodsdemandId getId() {
        return this.id;
    }
    
    public void setId(GoodsdemandId id) {
        this.id = id;
    }

    
    @Column(name="DemandTitle", length=50)
    public String getDemandTitle() {
        return this.demandTitle;
    }
    
    public void setDemandTitle(String demandTitle) {
        this.demandTitle = demandTitle;
    }

    
    @Column(name="DemandSide", length=50)
    public String getDemandSide() {
        return this.demandSide;
    }
    
    public void setDemandSide(String demandSide) {
        this.demandSide = demandSide;
    }

    
    @Column(name="DemandCity", length=30)
    public String getDemandCity() {
        return this.demandCity;
    }
    
    public void setDemandCity(String demandCity) {
        this.demandCity = demandCity;
    }

    
    @Column(name="DemandAddress", length=80)
    public String getDemandAddress() {
        return this.demandAddress;
    }
    
    public void setDemandAddress(String demandAddress) {
        this.demandAddress = demandAddress;
    }

    
    @Column(name="DemandPerson", length=30)
    public String getDemandPerson() {
        return this.demandPerson;
    }
    
    public void setDemandPerson(String demandPerson) {
        this.demandPerson = demandPerson;
    }

    
    @Column(name="DemandTel", length=30)
    public String getDemandTel() {
        return this.demandTel;
    }
    
    public void setDemandTel(String demandTel) {
        this.demandTel = demandTel;
    }

    
    @Column(name="DemandGoods", length=30)
    public String getDemandGoods() {
        return this.demandGoods;
    }
    
    public void setDemandGoods(String demandGoods) {
        this.demandGoods = demandGoods;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DemandValidity", length=10)
    public Date getDemandValidity() {
        return this.demandValidity;
    }
    
    public void setDemandValidity(Date demandValidity) {
        this.demandValidity = demandValidity;
    }

    
    @Column(name="DemandContent", length=1000)
    public String getDemandContent() {
        return this.demandContent;
    }
    
    public void setDemandContent(String demandContent) {
        this.demandContent = demandContent;
    }

    
    @Column(name="DemandPicture", length=50)
    public String getDemandPicture() {
        return this.demandPicture;
    }
    
    public void setDemandPicture(String demandPicture) {
        this.demandPicture = demandPicture;
    }

    
    @Column(name="DemandVideo", length=50)
    public String getDemandVideo() {
        return this.demandVideo;
    }
    
    public void setDemandVideo(String demandVideo) {
        this.demandVideo = demandVideo;
    }

    
    @Column(name="DemandStatus", length=10)
    public String getDemandStatus() {
        return this.demandStatus;
    }
    
    public void setDemandStatus(String demandStatus) {
        this.demandStatus = demandStatus;
    }




}


