package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JournalId generated by hbm2java
 */
@Embeddable
public class JournalId  implements java.io.Serializable {


     private Date jourTime;
     private String userId;

    public JournalId() {
    }

    public JournalId(Date jourTime, String userId) {
       this.jourTime = jourTime;
       this.userId = userId;
    }
   


    @Column(name="JourTime", nullable=false, length=23)
    public Date getJourTime() {
        return this.jourTime;
    }
    
    public void setJourTime(Date jourTime) {
        this.jourTime = jourTime;
    }


    @Column(name="UserId", nullable=false, length=30)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JournalId) ) return false;
		 JournalId castOther = ( JournalId ) other; 
         
		 return ( (this.getJourTime()==castOther.getJourTime()) || ( this.getJourTime()!=null && castOther.getJourTime()!=null && this.getJourTime().equals(castOther.getJourTime()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getJourTime() == null ? 0 : this.getJourTime().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         return result;
   }   


}


