package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="message"
    ,schema="dbo"
    ,catalog="SptEducation"
)
public class Message  implements java.io.Serializable {


     private MessageId id;
     private String mcontent;

    public Message() {
    }

	
    public Message(MessageId id) {
        this.id = id;
    }
    public Message(MessageId id, String mcontent) {
       this.id = id;
       this.mcontent = mcontent;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="mtime", column=@Column(name="MTime", nullable=false, length=23) ), 
        @AttributeOverride(name="moutId", column=@Column(name="MOutId", nullable=false, length=20) ), 
        @AttributeOverride(name="minId", column=@Column(name="MInId", nullable=false, length=20) ) } )
    public MessageId getId() {
        return this.id;
    }
    
    public void setId(MessageId id) {
        this.id = id;
    }

    
    @Column(name="MContent", length=200)
    public String getMcontent() {
        return this.mcontent;
    }
    
    public void setMcontent(String mcontent) {
        this.mcontent = mcontent;
    }




}


