package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MessageId generated by hbm2java
 */
@Embeddable
public class MessageId  implements java.io.Serializable {


     private Date mtime;
     private String moutId;
     private String minId;

    public MessageId() {
    }

    public MessageId(Date mtime, String moutId, String minId) {
       this.mtime = mtime;
       this.moutId = moutId;
       this.minId = minId;
    }
   


    @Column(name="MTime", nullable=false, length=23)
    public Date getMtime() {
        return this.mtime;
    }
    
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }


    @Column(name="MOutId", nullable=false, length=20)
    public String getMoutId() {
        return this.moutId;
    }
    
    public void setMoutId(String moutId) {
        this.moutId = moutId;
    }


    @Column(name="MInId", nullable=false, length=20)
    public String getMinId() {
        return this.minId;
    }
    
    public void setMinId(String minId) {
        this.minId = minId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MessageId) ) return false;
		 MessageId castOther = ( MessageId ) other; 
         
		 return ( (this.getMtime()==castOther.getMtime()) || ( this.getMtime()!=null && castOther.getMtime()!=null && this.getMtime().equals(castOther.getMtime()) ) )
 && ( (this.getMoutId()==castOther.getMoutId()) || ( this.getMoutId()!=null && castOther.getMoutId()!=null && this.getMoutId().equals(castOther.getMoutId()) ) )
 && ( (this.getMinId()==castOther.getMinId()) || ( this.getMinId()!=null && castOther.getMinId()!=null && this.getMinId().equals(castOther.getMinId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMtime() == null ? 0 : this.getMtime().hashCode() );
         result = 37 * result + ( getMoutId() == null ? 0 : this.getMoutId().hashCode() );
         result = 37 * result + ( getMinId() == null ? 0 : this.getMinId().hashCode() );
         return result;
   }   


}


