package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Speapply generated by hbm2java
 */
@Entity
@Table(name="speapply"
    ,schema="dbo"
    ,catalog="SptEducation"
)
public class Speapply  implements java.io.Serializable {


     private String userId;
     private String saidcardPhoto;
     private String sapersonDescribe;
     private String saeducationBackground;
     private String sasupportLevel;
     private Date satime;
     private String saputonghua;

    public Speapply() {
    }

	
    public Speapply(String userId) {
        this.userId = userId;
    }
    public Speapply(String userId, String saidcardPhoto, String sapersonDescribe, String saeducationBackground, String sasupportLevel, Date satime, String saputonghua) {
       this.userId = userId;
       this.saidcardPhoto = saidcardPhoto;
       this.sapersonDescribe = sapersonDescribe;
       this.saeducationBackground = saeducationBackground;
       this.sasupportLevel = sasupportLevel;
       this.satime = satime;
       this.saputonghua = saputonghua;
    }
   
     @Id 

    
    @Column(name="UserId", unique=true, nullable=false, length=30)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="SAIdcardPhoto", length=50)
    public String getSaidcardPhoto() {
        return this.saidcardPhoto;
    }
    
    public void setSaidcardPhoto(String saidcardPhoto) {
        this.saidcardPhoto = saidcardPhoto;
    }

    
    @Column(name="SAPersonDescribe", length=200)
    public String getSapersonDescribe() {
        return this.sapersonDescribe;
    }
    
    public void setSapersonDescribe(String sapersonDescribe) {
        this.sapersonDescribe = sapersonDescribe;
    }

    
    @Column(name="SAEducationBackground", length=30)
    public String getSaeducationBackground() {
        return this.saeducationBackground;
    }
    
    public void setSaeducationBackground(String saeducationBackground) {
        this.saeducationBackground = saeducationBackground;
    }

    
    @Column(name="SASupportLevel", length=5)
    public String getSasupportLevel() {
        return this.sasupportLevel;
    }
    
    public void setSasupportLevel(String sasupportLevel) {
        this.sasupportLevel = sasupportLevel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SATime", length=10)
    public Date getSatime() {
        return this.satime;
    }
    
    public void setSatime(Date satime) {
        this.satime = satime;
    }

    
    @Column(name="SAPutonghua", length=5)
    public String getSaputonghua() {
        return this.saputonghua;
    }
    
    public void setSaputonghua(String saputonghua) {
        this.saputonghua = saputonghua;
    }




}


