package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpeduId generated by hbm2java
 */
@Embeddable
public class SpeduId  implements java.io.Serializable {


     private Date speTime;
     private String userId;

    public SpeduId() {
    }

    public SpeduId(Date speTime, String userId) {
       this.speTime = speTime;
       this.userId = userId;
    }
   


    @Column(name="SpeTime", nullable=false, length=23)
    public Date getSpeTime() {
        return this.speTime;
    }
    
    public void setSpeTime(Date speTime) {
        this.speTime = speTime;
    }


    @Column(name="UserId", nullable=false, length=30)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SpeduId) ) return false;
		 SpeduId castOther = ( SpeduId ) other; 
         
		 return ( (this.getSpeTime()==castOther.getSpeTime()) || ( this.getSpeTime()!=null && castOther.getSpeTime()!=null && this.getSpeTime().equals(castOther.getSpeTime()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSpeTime() == null ? 0 : this.getSpeTime().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         return result;
   }   


}


