package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Spedu generated by hbm2java
 */
@Entity
@Table(name="spedu"
    ,schema="dbo"
    ,catalog="SptEducation"
)
public class Spedu  implements java.io.Serializable {


     private SpeduId id;
     private String speTitle;
     private String speSchool;
     private String speCity;
     private String speAddress;
     private String spePerson;
     private String speTel;
     private String speQuantity;
     private Date speStartTime;
     private Date speEndTime;
     private String speContent;
     private String spePicture;
     private String speVideo;
     private String demandStatus;

    public Spedu() {
    }

	
    public Spedu(SpeduId id) {
        this.id = id;
    }
    public Spedu(SpeduId id, String speTitle, String speSchool, String speCity, String speAddress, String spePerson, String speTel, String speQuantity, Date speStartTime, Date speEndTime, String speContent, String spePicture, String speVideo, String demandStatus) {
       this.id = id;
       this.speTitle = speTitle;
       this.speSchool = speSchool;
       this.speCity = speCity;
       this.speAddress = speAddress;
       this.spePerson = spePerson;
       this.speTel = speTel;
       this.speQuantity = speQuantity;
       this.speStartTime = speStartTime;
       this.speEndTime = speEndTime;
       this.speContent = speContent;
       this.spePicture = spePicture;
       this.speVideo = speVideo;
       this.demandStatus = demandStatus;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="speTime", column=@Column(name="SpeTime", nullable=false, length=23) ), 
        @AttributeOverride(name="userId", column=@Column(name="UserId", nullable=false, length=30) ) } )
    public SpeduId getId() {
        return this.id;
    }
    
    public void setId(SpeduId id) {
        this.id = id;
    }

    
    @Column(name="SpeTitle", length=50)
    public String getSpeTitle() {
        return this.speTitle;
    }
    
    public void setSpeTitle(String speTitle) {
        this.speTitle = speTitle;
    }

    
    @Column(name="SpeSchool", length=50)
    public String getSpeSchool() {
        return this.speSchool;
    }
    
    public void setSpeSchool(String speSchool) {
        this.speSchool = speSchool;
    }

    
    @Column(name="SpeCity", length=30)
    public String getSpeCity() {
        return this.speCity;
    }
    
    public void setSpeCity(String speCity) {
        this.speCity = speCity;
    }

    
    @Column(name="SpeAddress", length=80)
    public String getSpeAddress() {
        return this.speAddress;
    }
    
    public void setSpeAddress(String speAddress) {
        this.speAddress = speAddress;
    }

    
    @Column(name="SpePerson", length=30)
    public String getSpePerson() {
        return this.spePerson;
    }
    
    public void setSpePerson(String spePerson) {
        this.spePerson = spePerson;
    }

    
    @Column(name="SpeTel", length=30)
    public String getSpeTel() {
        return this.speTel;
    }
    
    public void setSpeTel(String speTel) {
        this.speTel = speTel;
    }

    
    @Column(name="SpeQuantity", length=30)
    public String getSpeQuantity() {
        return this.speQuantity;
    }
    
    public void setSpeQuantity(String speQuantity) {
        this.speQuantity = speQuantity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SpeStartTime", length=10)
    public Date getSpeStartTime() {
        return this.speStartTime;
    }
    
    public void setSpeStartTime(Date speStartTime) {
        this.speStartTime = speStartTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SpeEndTime", length=10)
    public Date getSpeEndTime() {
        return this.speEndTime;
    }
    
    public void setSpeEndTime(Date speEndTime) {
        this.speEndTime = speEndTime;
    }

    
    @Column(name="SpeContent", length=1000)
    public String getSpeContent() {
        return this.speContent;
    }
    
    public void setSpeContent(String speContent) {
        this.speContent = speContent;
    }

    
    @Column(name="SpePicture", length=50)
    public String getSpePicture() {
        return this.spePicture;
    }
    
    public void setSpePicture(String spePicture) {
        this.spePicture = spePicture;
    }

    
    @Column(name="SpeVideo", length=50)
    public String getSpeVideo() {
        return this.speVideo;
    }
    
    public void setSpeVideo(String speVideo) {
        this.speVideo = speVideo;
    }

    
    @Column(name="DemandStatus", length=10)
    public String getDemandStatus() {
        return this.demandStatus;
    }
    
    public void setDemandStatus(String demandStatus) {
        this.demandStatus = demandStatus;
    }




}


