package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpesignupId generated by hbm2java
 */
@Embeddable
public class SpesignupId  implements java.io.Serializable {


     private Date sstime;
     private String userId;
     private Date speTime;
     private String speId;

    public SpesignupId() {
    }

    public SpesignupId(Date sstime, String userId, Date speTime, String speId) {
       this.sstime = sstime;
       this.userId = userId;
       this.speTime = speTime;
       this.speId = speId;
    }
   


    @Column(name="SSTime", nullable=false, length=23)
    public Date getSstime() {
        return this.sstime;
    }
    
    public void setSstime(Date sstime) {
        this.sstime = sstime;
    }


    @Column(name="UserId", nullable=false, length=20)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }


    @Column(name="SpeTime", nullable=false, length=23)
    public Date getSpeTime() {
        return this.speTime;
    }
    
    public void setSpeTime(Date speTime) {
        this.speTime = speTime;
    }


    @Column(name="SpeId", nullable=false, length=30)
    public String getSpeId() {
        return this.speId;
    }
    
    public void setSpeId(String speId) {
        this.speId = speId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SpesignupId) ) return false;
		 SpesignupId castOther = ( SpesignupId ) other; 
         
		 return ( (this.getSstime()==castOther.getSstime()) || ( this.getSstime()!=null && castOther.getSstime()!=null && this.getSstime().equals(castOther.getSstime()) ) )
 && ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getSpeTime()==castOther.getSpeTime()) || ( this.getSpeTime()!=null && castOther.getSpeTime()!=null && this.getSpeTime().equals(castOther.getSpeTime()) ) )
 && ( (this.getSpeId()==castOther.getSpeId()) || ( this.getSpeId()!=null && castOther.getSpeId()!=null && this.getSpeId().equals(castOther.getSpeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSstime() == null ? 0 : this.getSstime().hashCode() );
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getSpeTime() == null ? 0 : this.getSpeTime().hashCode() );
         result = 37 * result + ( getSpeId() == null ? 0 : this.getSpeId().hashCode() );
         return result;
   }   


}


