package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Spesignup generated by hbm2java
 */
@Entity
@Table(name="spesignup"
    ,schema="dbo"
    ,catalog="SptEducation"
)
public class Spesignup  implements java.io.Serializable {


     private SpesignupId id;
     private String speTitle;

    public Spesignup() {
    }

	
    public Spesignup(SpesignupId id) {
        this.id = id;
    }
    public Spesignup(SpesignupId id, String speTitle) {
       this.id = id;
       this.speTitle = speTitle;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sstime", column=@Column(name="SSTime", nullable=false, length=23) ), 
        @AttributeOverride(name="userId", column=@Column(name="UserId", nullable=false, length=20) ), 
        @AttributeOverride(name="speTime", column=@Column(name="SpeTime", nullable=false, length=23) ), 
        @AttributeOverride(name="speId", column=@Column(name="SpeId", nullable=false, length=30) ) } )
    public SpesignupId getId() {
        return this.id;
    }
    
    public void setId(SpesignupId id) {
        this.id = id;
    }

    
    @Column(name="SpeTitle", length=50)
    public String getSpeTitle() {
        return this.speTitle;
    }
    
    public void setSpeTitle(String speTitle) {
        this.speTitle = speTitle;
    }




}


