package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,schema="dbo"
    ,catalog="SptEducation"
)
public class Users  implements java.io.Serializable {


     private String userId;
     private String userName;
     private String userPwd;
     private String userRealName;
     private String userGender;
     private String userCard;
     private String userTel;
     private String userEmail;
     private String userCity;
     private String userOccupation;
     private Date userBirtnday;

    public Users() {
    }

	
    public Users(String userId, String userName) {
        this.userId = userId;
        this.userName = userName;
    }
    public Users(String userId, String userName, String userPwd, String userRealName, String userGender, String userCard, String userTel, String userEmail, String userCity, String userOccupation, Date userBirtnday) {
       this.userId = userId;
       this.userName = userName;
       this.userPwd = userPwd;
       this.userRealName = userRealName;
       this.userGender = userGender;
       this.userCard = userCard;
       this.userTel = userTel;
       this.userEmail = userEmail;
       this.userCity = userCity;
       this.userOccupation = userOccupation;
       this.userBirtnday = userBirtnday;
    }
   
     @Id 

    
    @Column(name="UserId", unique=true, nullable=false, length=50)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="UserName", nullable=false, length=30)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="UserPwd", length=30)
    public String getUserPwd() {
        return this.userPwd;
    }
    
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    
    @Column(name="UserRealName", length=30)
    public String getUserRealName() {
        return this.userRealName;
    }
    
    public void setUserRealName(String userRealName) {
        this.userRealName = userRealName;
    }

    
    @Column(name="UserGender", length=5)
    public String getUserGender() {
        return this.userGender;
    }
    
    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }

    
    @Column(name="UserCard", length=50)
    public String getUserCard() {
        return this.userCard;
    }
    
    public void setUserCard(String userCard) {
        this.userCard = userCard;
    }

    
    @Column(name="UserTel", length=30)
    public String getUserTel() {
        return this.userTel;
    }
    
    public void setUserTel(String userTel) {
        this.userTel = userTel;
    }

    
    @Column(name="UserEmail", length=30)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    @Column(name="UserCity", length=30)
    public String getUserCity() {
        return this.userCity;
    }
    
    public void setUserCity(String userCity) {
        this.userCity = userCity;
    }

    
    @Column(name="UserOccupation", length=50)
    public String getUserOccupation() {
        return this.userOccupation;
    }
    
    public void setUserOccupation(String userOccupation) {
        this.userOccupation = userOccupation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UserBirtnday", length=10)
    public Date getUserBirtnday() {
        return this.userBirtnday;
    }
    
    public void setUserBirtnday(Date userBirtnday) {
        this.userBirtnday = userBirtnday;
    }




}


