package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userapply generated by hbm2java
 */
@Entity
@Table(name="userapply"
    ,schema="dbo"
    ,catalog="SptEducation"
)
public class Userapply  implements java.io.Serializable {


     private String userId;
     private String userCardPath;
     private String userStatus;

    public Userapply() {
    }

	
    public Userapply(String userId) {
        this.userId = userId;
    }
    public Userapply(String userId, String userCardPath, String userStatus) {
       this.userId = userId;
       this.userCardPath = userCardPath;
       this.userStatus = userStatus;
    }
   
     @Id 

    
    @Column(name="UserId", unique=true, nullable=false, length=30)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="UserCardPath", length=50)
    public String getUserCardPath() {
        return this.userCardPath;
    }
    
    public void setUserCardPath(String userCardPath) {
        this.userCardPath = userCardPath;
    }

    
    @Column(name="UserStatus", length=10)
    public String getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }




}


