package com.qdu.pojo;
// Generated 2019-1-1 18:49:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Useridentity generated by hbm2java
 */
@Entity
@Table(name="useridentity"
    ,schema="dbo"
    ,catalog="SptEducation"
)
public class Useridentity  implements java.io.Serializable {


     private String userId;
     private Integer userStatue1;
     private Integer userStatue2;

    public Useridentity() {
    }

	
    public Useridentity(String userId) {
        this.userId = userId;
    }
    public Useridentity(String userId, Integer userStatue1, Integer userStatue2) {
       this.userId = userId;
       this.userStatue1 = userStatue1;
       this.userStatue2 = userStatue2;
    }
   
     @Id 

    
    @Column(name="UserId", unique=true, nullable=false, length=50)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="UserStatue1")
    public Integer getUserStatue1() {
        return this.userStatue1;
    }
    
    public void setUserStatue1(Integer userStatue1) {
        this.userStatue1 = userStatue1;
    }

    
    @Column(name="UserStatue2")
    public Integer getUserStatue2() {
        return this.userStatue2;
    }
    
    public void setUserStatue2(Integer userStatue2) {
        this.userStatue2 = userStatue2;
    }




}


